// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gssoucyulzmoppjmdasl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzc291Y3l1bHptb3Bwam1kYXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTYxNjQsImV4cCI6MjA2NTU5MjE2NH0.PBJPHz1ITg0E0ot6I5xoehVUCd9hbJn0JRMDTX4chcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});